module.exports = {

  'ALL_GENRES': ['Crime', 'Drama', 'Comedy', 'Action', 'Thriller', 'Adventure', 'Science Fiction', 'Animation',
  'Family', 'Romance', 'Mystery', 'Music', 'Horror', 'Fantasy', 'Documentary', 'War', 'Western', 'History',
  'TV Movie', 'Foreign'],

  'TOP_10': {
    'Crime': '[{"title":"The Shawshank Redemption","rating":8.5,"vote_count":8358,"genre":"Crime","$$hashKey":"object:83"},{"title":"The Godfather","rating":8.5,"vote_count":6024,"genre":"Crime","$$hashKey":"object:84"},{"title":"Dear Zachary: A Letter to a Son About His Father","rating":8.4,"vote_count":146,"genre":"Crime","$$hashKey":"object:85"},{"title":"A Brighter Summer Day","rating":8.4,"vote_count":45,"genre":"Crime","$$hashKey":"object:86"},{"title":"Pixote","rating":8.4,"vote_count":24,"genre":"Crime","$$hashKey":"object:87"},{"title":"The Dark Knight","rating":8.3,"vote_count":12269,"genre":"Crime","$$hashKey":"object:88"},{"title":"Pulp Fiction","rating":8.3,"vote_count":8670,"genre":"Crime","$$hashKey":"object:89"},{"title":"The Godfather: Part II","rating":8.3,"vote_count":3418,"genre":"Crime","$$hashKey":"object:90"},{"title":"Once Upon a Time in America","rating":8.3,"vote_count":1104,"genre":"Crime","$$hashKey":"object:91"},{"title":"Leon: The Professional","rating":8.2,"vote_count":4293,"genre":"Crime","$$hashKey":"object:92"}]',
    'Drama': '[{"title":"Dilwale Dulhania Le Jayenge", "rating":9.1, "vote_count":661}, {"title":"Sansho the Bailiff", "rating":8.7, "vote_count":68}, {"title":"Cosy Dens", "rating":8.6, "vote_count":23}, {"title":"The Shawshank Redemption", "rating":8.5, "vote_count":8358}, {"title":"The Godfather", "rating":8.5, "vote_count":6024}, {"title":"Your Name.", "rating":8.5, "vote_count":1030}, {"title":"The Human Condition I: No Greater Love", "rating":8.5, "vote_count":42}, {"title":"The Human Condition II: Road to Eternity", "rating":8.5, "vote_count":31}, {"title":"Parched", "rating":8.5, "vote_count":23}, {"title":"The Man Who Sleeps", "rating":8.5, "vote_count":22}]',
    'Comedy': '[{"title":"Dilwale Dulhania Le Jayenge","rating":9.1,"vote_count":661,"genre":"Comedy","$$hashKey":"object:43"},{"title":"Cosy Dens","rating":8.6,"vote_count":23,"genre":"Comedy","$$hashKey":"object:44"},{"title":"Too Many Cooks","rating":8.5,"vote_count":24,"genre":"Comedy","$$hashKey":"object:45"},{"title":"Bill Hicks: Revelations","rating":8.5,"vote_count":21,"genre":"Comedy","$$hashKey":"object:46"},{"title":"Bo Burnham: Make Happy","rating":8.4,"vote_count":56,"genre":"Comedy","$$hashKey":"object:47"},{"title":"Life Is Beautiful","rating":8.3,"vote_count":3643,"genre":"Comedy","$$hashKey":"object:48"},{"title":"In a Heartbeat","rating":8.3,"vote_count":146,"genre":"Comedy","$$hashKey":"object:49"},{"title":"The Present","rating":8.3,"vote_count":52,"genre":"Comedy","$$hashKey":"object:50"},{"title":"Toto, Peppino, and the Hussy","rating":8.3,"vote_count":48,"genre":"Comedy","$$hashKey":"object:51"},{"title":"Louis C.K.: Chewed Up","rating":8.3,"vote_count":46,"genre":"Comedy","$$hashKey":"object:52"}]',
    'Action': '[{"title":"The Dark Knight", "rating":8.3, "vote_count":12269}, {"title":"The Empire Strikes Back", "rating":8.2, "vote_count":5998}, {"title":"Seven Samurai", "rating":8.2, "vote_count":892}, {"title":"Band of Brothers", "rating":8.2, "vote_count":725}, {"title":"Harakiri", "rating":8.2, "vote_count":136}, {"title":"Generation War", "rating":8.2, "vote_count":70}, {"title":"Inception", "rating":8.1, "vote_count":14075}, {"title":"The Lord of the Rings: The Return of the King", "rating":8.1, "vote_count":8226}, {"title":"Star Wars", "rating":8.1, "vote_count":6778}, {"title":"Love Exposure", "rating":8.1, "vote_count":89}]',
    'Thriller': '[{"title":"The Dark Knight", "rating":8.3, "vote_count":12269}, {"title":"Pulp Fiction", "rating":8.3, "vote_count":8670}, {"title":"Psycho", "rating":8.3, "vote_count":2405}, {"title":"Black Mirror: White Christmas", "rating":8.3, "vote_count":211}, {"title":"Leon: The Professional", "rating":8.2, "vote_count":4293}, {"title":"Rear Window", "rating":8.2, "vote_count":1531}, {"title":"High and Low", "rating":8.2, "vote_count":123}, {"title":"Le Trou", "rating":8.2, "vote_count":73}, {"title":"Inception", "rating":8.1, "vote_count":14075}, {"title":"Se7en", "rating":8.1, "vote_count":5915}]',
    'Adventure': '[{"title":"Spirited Away", "rating":8.3, "vote_count":3968}, {"title":"The Art of Flight", "rating":8.3, "vote_count":70}, {"title":"The Empire Strikes Back", "rating":8.2, "vote_count":5998}, {"title":"Howl\'s Moving Castle", "rating":8.2, "vote_count":2049}, {"title":"Princess Mononoke", "rating":8.2, "vote_count":2041}, {"title":"A Dog\'s Will", "rating":8.2, "vote_count":120}, {"title":"Over the Garden Wall", "rating":8.2, "vote_count":52}, {"title":"Long Way Round", "rating":8.2, "vote_count":24}, {"title":"Inception", "rating":8.1, "vote_count":14075}, {"title":"Interstellar", "rating":8.1, "vote_count":11187}]',
    'Science Fiction': '[{"title":"Doctor Who: The Time of the Doctor", "rating":8.4, "vote_count":61}, {"title":"Black Mirror: White Christmas", "rating":8.3, "vote_count":211}, {"title":"The Empire Strikes Back", "rating":8.2, "vote_count":5998}, {"title":"Inception", "rating":8.1, "vote_count":14075}, {"title":"Interstellar", "rating":8.1, "vote_count":11187}, {"title":"Star Wars", "rating":8.1, "vote_count":6778}, {"title":"The End of Evangelion", "rating":8.1, "vote_count":124}, {"title":"Back to the Future", "rating":8, "vote_count":6239}, {"title":"A Clockwork Orange", "rating":8, "vote_count":3432}, {"title":"Metropolis", "rating":8, "vote_count":666}]',
  },

  'RECOMMEND': {
    'Tales of Terror': [13581, 9707, 13122, 13436, 37527],
    'Sansho the Bailiff': [19404, 15387, 278, 238, 372058],
    'Shrek': [82702, 137106, 812, 40623, 11970],
  },

  'BEST_GENRES': {
    '1870': '[{"genre":"Documentary","rating":6.2},{"genre":"Action","rating":0},{"genre":"Adventure","rating":0},{"genre":"Animation","rating":0},{"genre":"Comedy","rating":0},{"genre":"Crime","rating":0},{"genre":"Drama","rating":0},{"genre":"Family","rating":0},{"genre":"Fantasy","rating":0},{"genre":"Foreign","rating":0},{"genre":"History","rating":0},{"genre":"Horror","rating":0},{"genre":"Music","rating":0},{"genre":"Mystery","rating":0},{"genre":"Romance","rating":0},{"genre":"Science Fiction","rating":0},{"genre":"Thriller","rating":0},{"genre":"TV Movie","rating":0},{"genre":"War","rating":0},{"genre":"Western","rating":0}]',
    '1910': '[{"genre":"Drama","rating":7},{"genre":"Animation","rating":6.95},{"genre":"Romance","rating":6.9},{"genre":"Comedy","rating":6.727273},{"genre":"History","rating":6.6},{"genre":"War","rating":6.55},{"genre":"Horror","rating":6.4},{"genre":"Science Fiction","rating":6.4},{"genre":"Action","rating":0},{"genre":"Adventure","rating":0},{"genre":"Crime","rating":0},{"genre":"Documentary","rating":0},{"genre":"Family","rating":0},{"genre":"Fantasy","rating":0},{"genre":"Foreign","rating":0},{"genre":"Music","rating":0},{"genre":"Mystery","rating":0},{"genre":"Thriller","rating":0},{"genre":"TV Movie","rating":0},{"genre":"Western","rating":0}]'
  }
}
